### ISSUE TITLE
where this error coming from?

### ISSUE THREAD

**Issue by kholiqsantosa** [vanhbakaa/Notpixel-bot#119]
```
[Not pixel] | 2024-11-12 07:37:17 | INFO     | 127 - #KING | Loading proxy from
cache...
Traceback (most recent call last):
  File "/root/bot/Notpixel-bot/main.py", line 13, in <module>
    asyncio.run(main())
  File "/usr/lib/python3.10/asyncio/runners.py", line 44, in run
    return loop.run_until_complete(main)
  File "/usr/lib/python3.10/asyncio/base_events.py", line 649, in run_until_comp
lete
    return future.result()
  File "/root/bot/Notpixel-bot/main.py", line 8, in main
    await process()
  File "/root/bot/Notpixel-bot/bot/utils/launcher.py", line 177, in process
    await run_tapper1(tg_clients=tg_clients)
  File "/root/bot/Notpixel-bot/bot/core/tapper.py", line 874, in run_tapper1
    proxy=await lc.get_proxy(tg_client.name), ua=await get_user_agent(tg_client.
name))
  File "/root/bot/Notpixel-bot/bot/core/tapper.py", line 857, in get_user_agent
    if session_name not in list(user_agents.keys()):
AttributeError: 'list' object has no attribute 'keys'
```

**Comment by vanhbakaa** [comment]
reinstall
