### ISSUE TITLE
Issues 

### ISSUE THREAD

**Issue by unpredictablemahi** [vanhbakaa/Notpixel-bot#13]
I got this issue help me with it ... 
Wanna use query I'd method 

Traceback (most recent call last):
  File "/home/ubuntu/Notpixel-bot/main.py", line 4, in <module>
    from bot.utils.launcher import process
  File "/home/ubuntu/Notpixel-bot/bot/utils/__init__.py", line 2, in <module>
    from . import launcher
  File "/home/ubuntu/Notpixel-bot/bot/utils/launcher.py", line 10, in <module>
    from bot.config import settings
  File "/home/ubuntu/Notpixel-bot/bot/config/__init__.py", line 1, in <module>
    from .config import settings
  File "/home/ubuntu/Notpixel-bot/bot/config/config.py", line 22, in <module>
    settings = Settings()
               ^^^^^^^^^^
  File "/home/ubuntu/NotPixel/venv/lib/python3.12/site-packages/pydantic_settings/main.py", line 84, in __init__
    super().__init__(
  File "/home/ubuntu/NotPixel/venv/lib/python3.12/site-packages/pydantic/main.py", line 171, in __init__
    self.__pydantic_validator__.validate_python(data, self_instance=self)
pydantic_core._pydantic_core.ValidationError: 2 validation errors for Settings
API_ID
  Field required [type=missing, input_value={'REF_LINK': 'True', 'X3P...ROXY_FROM_FILE': 'True'}, input_type=dict]
    For further information visit https://errors.pydantic.dev/2.6/v/missing
API_HASH
  Field required [type=missing, input_value={'REF_LINK': 'True', 'X3P...ROXY_FROM_FILE': 'True'}, input_type=dict]
    For further information visit https://errors.pydantic.dev/2.6/v/missing

**Comment by vanhbakaa** [comment]
Put random number in api id and api hash if u use query
