### ISSUE TITLE
what is the issue 

### ISSUE THREAD

**Issue by savan878** [vanhbakaa/Notpixel-bot#44]
PS C:\Users\savan\Notpixel-bot-4> python main.py
Traceback (most recent call last):
  File "C:\Users\savan\Notpixel-bot-4\main.py", line 4, in <module>
    from bot.utils.launcher import process
  File "C:\Users\savan\Notpixel-bot-4\bot\utils\__init__.py", line 2, in <module>
    from . import launcher
  File "C:\Users\savan\Notpixel-bot-4\bot\utils\launcher.py", line 10, in <module>
    from bot.config import settings
  File "C:\Users\savan\Notpixel-bot-4\bot\config\__init__.py", line 1, in <module>
    from .config import settings
  File "C:\Users\savan\Notpixel-bot-4\bot\config\config.py", line 26, in <module>
    settings = Settings()
               ^^^^^^^^^^
  File "C:\Users\savan\AppData\Roaming\Python\Python312\site-packages\pydantic_settings\main.py", line 84, in __init__
    super().__init__(
  File "C:\Users\savan\AppData\Roaming\Python\Python312\site-packages\pydantic\main.py", line 171, in __init__
    self.__pydantic_validator__.validate_python(data, self_instance=self)
pydantic_core._pydantic_core.ValidationError: 2 validation errors for Settings
API_ID
  Field required [type=missing, input_value={}, input_type=dict]
    For further information visit https://errors.pydantic.dev/2.6/v/missing
API_HASH
  Field required [type=missing, input_value={}, input_type=dict]
    For further information visit https://errors.pydantic.dev/2.6/v/missing
PS C:\Users\savan\Notpixel-bot-4> ^C
PS C:\Users\savan\Notpixel-bot-4>

**Comment by vanhbakaa** [comment]
U are missing api id and api hash in .env
