### ISSUE TITLE
x3points Input Error

### ISSUE THREAD

**Issue by AminSiddika** [vanhbakaa/Notpixel-bot#85]
`Traceback (most recent call last):
  File "/root/Notpixel-bot/main.py", line 4, in <module>
    from bot.utils.launcher import process
  File "/root/Notpixel-bot/bot/utils/__init__.py", line 2, in <module
>
    from . import launcher
  File "/root/Notpixel-bot/bot/utils/launcher.py", line 11, in <modul
e>
    from bot.config import settings
  File "/root/Notpixel-bot/bot/config/__init__.py", line 1, in <modul
e>
    from .config import settings
  File "/root/Notpixel-bot/bot/config/config.py", line 35, in <module
>
    settings = Settings()
               ^^^^^^^^^^
  File "/usr/local/lib/python3.11/dist-packages/pydantic_settings/mai
n.py", line 84, in __init__
    super().__init__(
  File "/usr/local/lib/python3.11/dist-packages/pydantic/main.py", li
ne 171, in __init__
    self.__pydantic_validator__.validate_python(data, self_instance=s
elf)
pydantic_core._pydantic_core.ValidationError: 1 validation error for
Settings
x3points
  Extra inputs are not permitted [type=extra_forbidden, input_value='
True', input_type=str]
    For further information visit https://errors.pydantic.dev/2.6/v/e
xtra_forbidden`

I hope your intention isn't  trash this repo...
I hope you will fix this issue as soon as possible because bot not starting..

**Comment by vanhbakaa** [comment]
You should update your .env file
