### ISSUE TITLE
error after add bot token and bot is not working

### ISSUE THREAD

**Issue by supmyhava** [vanhbakaa/Notpixel-bot#97]
root@od-big:~/Notpixel-bot# python3 main.py
Traceback (most recent call last):
  File "/root/Notpixel-bot/main.py", line 4, in <module>
    from bot.utils.launcher import process
  File "/root/Notpixel-bot/bot/utils/__init__.py", line 2, in <module>
    from . import launcher
  File "/root/Notpixel-bot/bot/utils/launcher.py", line 11, in <module>
    from bot.config import settings
  File "/root/Notpixel-bot/bot/config/__init__.py", line 1, in <module>
    from .config import settings
  File "/root/Notpixel-bot/bot/config/config.py", line 35, in <module>
    settings = Settings()
               ^^^^^^^^^^
  File "/root/.pyenv/versions/3.11.0/lib/python3.11/site-packages/pydantic_settings/main.py", line 84, in __init__
    super().__init__(
  File "/root/.pyenv/versions/3.11.0/lib/python3.11/site-packages/pydantic/main.py", line 171, in __init__
    self.__pydantic_validator__.validate_python(data, self_instance=self)
pydantic_core._pydantic_core.ValidationError: 1 validation error for Settings
bot_token
  Extra inputs are not permitted [type=extra_forbidden, input_value='7379848719:AAGkKpYnwYulvW1t4KU137E2cqgQoCB4TaA', input_type=str]
    For further information visit https://errors.pydantic.dev/2.6/v/extra_forbidden
root@od-big:~/Notpixel-bot# ls
Dockerfile  README.md  bot  cache  cgi  data.txt  docker-compose.yml  index.js  main.py  package.json  requirements.txt  run.bat  run.sh  sessions
root@od-big:~/Notpixel-bot# nano bot/config/config.py
root@od-big:~/Notpixel-bot# nano .env
root@od-big:~/Notpixel-bot# python3 main.py
2024-10-31 15:13:13 | INFO     | 81 - Detected 3 sessions | 0 proxies

Select an action:

    1. Run clicker (Session)
    2. Create session
    3. Run clicker (Query)

> 1
> Do you want to run the bot with multi-thread? (y/n) n
2024-10-31 15:13:17 | SUCCESS  | 89 - No change in js file: index-CMaLOjQu.js
2024-10-31 15:13:18 | SUCCESS  | 177 - 0504945571 | Logged in.
2024-10-31 15:13:18 | INFO     | 624 - 0504945571 | Pixel Balance: 265 | Pixel available to paint: 16 | User league: gold
2024-10-31 15:13:18 | INFO     | 634 - 0504945571 | Using the new painting method.
2024-10-31 15:13:19 | WARNING  | 18 - Server unreachable, retrying in 30 seconds, attempt 1/10

**Comment by vanhbakaa** [comment]
It's not error read closed issue
